# Generated by Django 3.2.5 on 2021-08-23 06:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('user_password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('login_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ログイン日')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField(null=None, unique=True, verbose_name='楽曲番号')),
                ('sid', models.CharField(max_length=255, null=None, unique=True, verbose_name='ファイル名')),
                ('music_name', models.CharField(max_length=255, verbose_name='曲名')),
                ('artist_name', models.CharField(max_length=255, verbose_name='アーティスト名')),
            ],
            options={
                'db_table': 'music_info',
            },
        ),
        migrations.CreateModel(
            name='ImpressionInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_num', models.IntegerField(default=1, verbose_name='クラス番号')),
                ('proba_hh', models.FloatField(default=0.0, verbose_name='High')),
                ('proba_mh', models.FloatField(default=0.0, verbose_name='MHigh')),
                ('proba_mm', models.FloatField(default=0.0, verbose_name='Middle')),
                ('proba_lm', models.FloatField(default=0.0, verbose_name='LMiddle')),
                ('proba_ll', models.FloatField(default=0.0, verbose_name='Low')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.musicinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account')),
            ],
            options={
                'db_table': 'impression_info',
            },
        ),
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ex_id', models.IntegerField(default=0, verbose_name='実験番号')),
                ('playlist_type', models.IntegerField(default=0, verbose_name='プレイリストのタイプ')),
                ('playlist_mid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='プレイリストの楽曲')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account')),
            ],
            options={
                'db_table': 'experiment_info',
            },
        ),
    ]
